# config: hyper paras

device: "cuda" #cuda'
data_path: "../data/simu_scalable/D_1000_T_4000.npy"
R: 0.8 # ratio of test


K_trend: 50 # number of trend factors
K_season: 0 # number of seasonal factors (frequency in the data)
n_season: 0 # for each season/freq, we need n component to approximate it as a GP-SDE

K_bias: 0 # number of bias factors

a0: 1
b0: 1
v: 1
fold: 1 # number of folds(random split) and take average,min:1,max:5'
fix_int: True

time_scale: 1 # time scale of the time-step, 
kernel:
  kernel_trend:
    type: "Matern_21" # GP kernel type, Matern_21 or Matern_23"
    lengthscale: 3 # lengthscale of kernel= torch.tensor(args.ls)
    variance: 3 # var of kernel
    noise: 1 # noise var of KF observation, will not be used actually

  kernel_season:
    type: "exp-periodic"
    freq_list:
      - 62.83185 # pi/84(0.0374), period from TIDER paper
    lengthscale_list:
      - 0.1
    noise: 1 # noise var of KF observation, will not be used actually


DAMPING_U: 0.5
DAMPING_tau: 0.9
DAMPING_W: 0.55

EVALU_T: 100

INNER_ITER: 1
THRE: 1.0e-4 # therethold of CEP innner iteration

